title: <font color="orange">Jinghao Cao </font> # your name (or website title) here
logo: "/images/profile_pic.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <font color="orange">von Karman Instructor in Computing and Mathematical Sciences at Caltech </font>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
github:
    is_project_page: false
    is_user_page: false

